import { Provider } from "@/components/ui/provider"


import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";



export const metadata = {
  title: "☢️DeepSeek",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning>
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
